### ISSUE TITLE
Use a Touch Screen

### ISSUE THREAD

**Issue by jonnius** [ubports/raspberry-pi#5]
Do tests and fill a wiki page with instructions how to reproduce (both software and hardware side).
 - [x] Output graphics to screen
 - [x] Use touch inputs

**Comment by SohnyBohny** [comment]
The official [Raspberry Pi Touch Display](https://www.raspberrypi.org/products/raspberry-pi-touch-display/) does work just out of the box using [Ubuntu MATE 16.04.2](https://ubuntu-mate.org/raspberry-pi/ubuntu-mate-16.04.2-desktop-armhf-raspberry-pi.img.xz)

Just plug & play (so I think no additional instructions is needed)

(Tested on June 24, 2018 on my Raspberry Pi 3)

**Comment by MenmuirMark** [comment]
The official Pi touchscreen works quite well on the Pi 3 with the current UT arm64 image.

**Comment by jonnius** [comment]
Great 👍
